name: Adding for self hosted server
on:
    push:
        branches: ['master']
jobs:
    First:
        runs-on: self-hosted
        steps:
        - name: Create Dir
          run: mkdir IAM_1
        - name: Create File inside Dir_IAM
          run: |
               cd IAM_1
               touch Hello.txt
          