name: Testing here
on: 
   push: 
        paths-ignore:
            - .github/workflows/index.yml   
        #paths:
        #   - .github/workflows/testing.yml #
        
# env:
#   u_name: Hello
#   pass: Nihanth // ENV variables at workflow level where every job can access it.
jobs:
    Setting_up_server:
    # env: 
    #   u_name: Hello
    #   pass: Nihanth // Env VAriables at job level where only single job and multiple steps inside can access it 
         runs-on: ubuntu-latest
         steps:
          - name: Creating folder
            run: |
               echo ${{ vars.MY_UNAME }} >> file2.txt #// Adding env variables at repo level
               echo ${{ secrets.MY_EXAMPLE_PASS }} >> file2.txt #// Adding Secrets varibales
          #  env:
          #    u_name: Nihanth
          #    pass: Nihanths // Env variables at step level where only a single step can access it
          #  run: |
          #    echo ${{ env.u_name }} >> file2.txt
          #    echo $pass >> file2.txt
          #    cat file2.txt
        #  -name: Doing 
        #    run: |
        #        touch file1.txt
        #        chmod 777 file1.txt
        #  - name: Writing
        #    run: |
        #        echo "ACTION FOLDER WITH FILE1" >> file1.txt
        #        cat file1.txt

         - name: Uploading the data in instance
           uses: actions/upload-artifact@v4
           with:
              name: Action_folder
              path: file2.txt

    Checking_again:
         needs: Setting_up_server
         runs-on: ubuntu-latest
         steps:
         - name: Downloading folder from instance
           uses: actions/download-artifact@v4
           with:
             name: Action_folder
         
         - name: Checking the previous data
           run: |
              cat file2.txt

            
                
         